### ISSUE TITLE
uPort-connect address

### ISSUE THREAD

**Issue by sjkelleyjr** [uport-project/uport-registry#38]
I see in the documentation we're supposed to use an address as the second parameter to a set call, but which address is this?  I'm using the uport-connect library and am getting returned:
`{ '@context': 'http://schema.org',
  '@type': 'Person',
  publicKey: '8854e2d2f5e5b01b0a5a018bd90f6936b7ea46f7ff108ca21',
  publicEncKey: 'xZAgm0v4gNpy5CCbcdKxC1VJMxuobpdITXr0hwCdRyg=',
  address: '2okWJAH3cY49CWcb4fRqUDy9QKJQpyfSoEc' }
`
Which of these is supposed to be the subject parameter?  

When I use the publicKey I get:

`(node:18521) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Invalid array length
`

When I use the address I get:

`(node:18483) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): BigNumber Error: new BigNumber() not a number: 2okWJAH3cY49CWcb4fRqUDy9QKJQpyfSoEc
`

or am I completely off base?

Thanks!

**Comment by sjkelleyjr** [comment]
Even if I use a known rinkeby address (0x7ffc57839b00206d1ad20c69a1981b489f772031) I still get the following error:

> Error: invalid address
>     at inputAddressFormatter (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/formatters.js:274:11)
>     at inputTransactionFormatter (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/formatters.js: 100:20)
>     at /home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:89:28
>     at Array.map (native)
>     at Method.formatInput (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:88:32)
>     at Method.toPayload (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:114:23)
>     at Eth.send [as sendTransaction] (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:139:30)
>     at SolidityFunction.sendTransaction (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:170:26)
>     at SolidityFunction.execute (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:256:37)
>     at registry.then.reg (/home/sj/uPort_node/test.js:27:37)

**Comment by sjkelleyjr** [comment]
Ah, didn't realize I needed to decode the uport-identity address.  Now when I do that I get:

> (node:13414) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Invalid number of arguments to Solidity function
> (node:13414) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


If I used the full decoded payload, and the original invalid address error if I use the address rather than the full payload (exactly the same error as using the address in the above comment).

**Comment by oed** [comment]
The second parameter is the `subject`, the one who the claim is for. The error you are getting is because of you passing an MNID. You need to decode the MNID to a regular ethereum address and then it should work.

**Comment by sjkelleyjr** [comment]
I've decoded the MNID and used the address attribute attached to it, as well as just using any old rinkeby address I can find.  When I do that I get the invalid address error discussed above:

> Error: invalid address
at inputAddressFormatter (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/formatters.js:274:11)
at inputTransactionFormatter (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/formatters.js: 100:20)
at /home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:89:28
at Array.map (native)
at Method.formatInput (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:88:32)
at Method.toPayload (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:114:23)
at Eth.send [as sendTransaction] (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:139:30)
at SolidityFunction.sendTransaction (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:170:26)
at SolidityFunction.execute (/home/sj/uPort_node/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:256:37)
at registry.then.reg (/home/sj/uPort_node/test.js:27:37)

**Comment by oed** [comment]
@sjkelleyjr can you post all the data of the parameters you are using in the call?
Are you using web3 or truffle-contract to interact with the contract?

**Comment by sjkelleyjr** [comment]
I've tried both.  Here's a simple case using web3:

const regsitryArtifact = require('uport-registry');
const Contract = require('truffle-contract');
const Registry = Contract(regsitryArtifact);
const Web3     = require('web3');

var web3 = new Web3(
    new Web3.providers.HttpProvider('https://rinkeby.infura.io/')
);

Registry.setProvider(web3.currentProvider)
let registry = Registry.deployed();

registry.then(reg => reg.set('test','0x7ffc57839b00206d1ad20c69a1981b489f772031', 'test'));


Even this basic test case is failing with the invalid address error.  Here's the code using uport-connect and truffle-contract:

const uport_lib    = require('uport-connect');
const qrcode       = require('qrcode-terminal');
const MNID         = require('mnid');
const regsitryArtifact = require('uport-registry');
const Contract = require('truffle-contract');
const Registry = Contract(regsitryArtifact)

const SimpleSigner = uport_lib.SimpleSigner;
const Connect      = uport_lib.Connect;

const uport = new Connect('ETHLend Integration', {
      clientId: '2oubHCrFbcqFCZs4SvUvBaeHds1WM82siCy',
      network: 'rinkeby',
      signer: SimpleSigner('117ca6e22aa3021e181b24852d475a5b7735eb255ae6e13ac889a06eb1cb7be4')
    })

const web3 = uport.getWeb3();

var instance;

Registry.setProvider(web3.currentProvider)
let registry = Registry.deployed().then(reg => {
  instance = reg;
});

uport.requestCredentials(['name'],
      uri => qrcode.generate(uri,{small:true}))
      .then(userProfile => {
        let addressPayload = MNID.decode(userProfile.address);
        instance.set('test',addressPayload.address,'test');
      })
      .catch(err => {
        console.log(err)
      })

**Comment by oed** [comment]
I think I've seen this problem once before with truffle-contract. Can you try to add `{ from: <your-address> }` as an aditional parameter in the `set` call?

**Comment by sjkelleyjr** [comment]
Progress:
(node:30647) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid JSON RPC response: ""

**Comment by oed** [comment]
Can you try it with the following code:

```js
const uport_lib = require('uport-connect');
const qrcode = require('qrcode-terminal');
const MNID = require('mnid');
const regsitryArtifact = require('uport-registry');
const Contract = require('truffle-contract');
const Registry = Contract(regsitryArtifact)

const SimpleSigner = uport_lib.SimpleSigner;
const Connect = uport_lib.Connect;

const uport = new Connect('ETHLend Integration', {
clientId: '2oubHCrFbcqFCZs4SvUvBaeHds1WM82siCy',
network: 'rinkeby',
signer: SimpleSigner('117ca6e22aa3021e181b24852d475a5b7735eb255ae6e13ac889a06eb1cb7be4'),
uriHandler: uri => qrcode.generate(uri,{small:true})
})

const web3 = uport.getWeb3();
var instance;
Registry.setProvider(web3.currentProvider)
let registry = Registry.deployed().then(reg => {
instance = reg;
});

uport.requestCredentials(['name']).then(userProfile => {
let addressPayload = MNID.decode(userProfile.address);
return instance.set('test',addressPayload.address,'test', {from: addressPayload.address});
}).then(tx => {
console.log(tx)
}).catch(err => {
console.log(err)
})
```

This example works for me.

**Comment by sjkelleyjr** [comment]
Brilliant! it's working!

Can you explain to me what the data in the tx object is?  My understanding is the ipfs-registry is a mapping between uport identity and IPFS hash.  It seems to me I should be able to see the IPFS hash somewhere, but I'm not seeing anything like that in the object:

```javascript
{ tx: '0x14e7b6db65413f0078cbad2836a65711ce5c821deb405b8724d4f7006a4d5f73',
  receipt: 
   { blockHash: '0x082f80ed34d8e4852b13f2729ff6f810fcb45d2c42b53f3c4824fa342409c56f',
     blockNumber: 1238618,
     contractAddress: null,
     cumulativeGasUsed: 60133,
     from: '0x7a6f8664a0216a5f8f4195f8a8c0fdda63c0631d',
     gasUsed: 60133,
     logs: [ [Object], [Object] ],
     logsBloom: '0x00000040040041000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000020000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000004004000000000000000000080000000000000000000000000000080000000000000000000080000000000000000000000000000004000000000800009000000000000000000000000080000000000000000000004000000004000020000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     status: '0x1',
     to: '0xabbcd5b340c80b5f1c0545c04c987b87310296ae',
     transactionHash: '0x14e7b6db65413f0078cbad2836a65711ce5c821deb405b8724d4f7006a4d5f73',
     transactionIndex: 0 },
  logs: 
   [ { address: '0x2cc31912b2b0f3075a87b3640923d45a26cef3ee',
       blockNumber: 1238618,
       transactionHash: '0x14e7b6db65413f0078cbad2836a65711ce5c821deb405b8724d4f7006a4d5f73',
       transactionIndex: 0,
       blockHash: '0x082f80ed34d8e4852b13f2729ff6f810fcb45d2c42b53f3c4824fa342409c56f',
       logIndex: 0,
       removed: false,
       event: 'Set',
       args: [Object] } ] }
```

Ideally I'd like to navigate to the ipfs hash in the browser and see the data.

I should be able to make a get call at this point with the key 'test' and subject '0x53ae8613c53c05b37b4a030d806fb73ff7258552' and get 'test' returned, correct? When I do that I get '0x7465737400000000000000000000000000000000000000000000000000000000' which is the registrationIdentifier, and not the key I'm expecting.  Code for reference:

```javascript
uport.requestCredentials(['name']).then(userProfile => {
    let addressPayload = MNID.decode(userProfile.address);
    console.log(addressPayload);
    return instance.set('test',addressPayload.address,'test', {from: addressPayload.address});
  }).then(tx => {
    const subject = tx.logs[0].args.subject;
    instance.get('test', subject, subject).then(value => {
      console.log(value);
    })
  }).catch(err => {
    console.log(err)
  })

```


Thank you for all your help, it's very much appreciated.

**Comment by oed** [comment]
When you call get you will get a bytes array encoded as a hex string returned. Since you use `'test'` as both the registrationIdentifier and the value they will be the same.

**Comment by sjkelleyjr** [comment]
Awesome!  Converting it from hex to string worked!  Thanks again for your help Joel!
